#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend mastermose.tech.holb20231tk0q1.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 153318-web-01 54.144.221.216:80
        server 153318-web-02 54.209.215.95:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
