#!/usr/bin/env bash
#this script will check if google with the ip 8.8.8.8 is
#reachable (ICMP) usingvthe ping command

if [ $# -eq 0 ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi
