#!/usr/bin/env bash
#This script will reconfigure nginx to listen to port 80 in a shorter way
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)"
