#!/usr/bin/env bash
#this scrip will create as well as delete a file, it will alstrap
#some of the process signals


file="/var/run/myscript.pid"
echo "$$" > $file

trap_all_these()
{
	trap 'echo "I hate the kill command"; rm -rf $file; exit' SIGTERM
	trap 'echo "Y U know love me?!"' SIGINT
	trap 'rm -rf $file; exit' SIGQUIT
}

while true
do
	echo "Infinity and beyond"
	sleep 2
	trap_all_these
done
