#!/usr/bin/env bash
#scipt to manage the process created by the file manahe_my_process
#with the options start stop restart

file="/var/run/my_process.pid"

if [ "$1" == "start" ]
then
	./manage_my_process &
	echo "$!" > $file
	echo "manage_my_process started"

elif [ "$1" == "stop" ]
then
	kill "$(cat $file)"
	rm -f $file
	echo "manage_my_process stopped"

elif [ "$1" == "restart" ]
then
	kill "$(cat $file)"
	rm -f $file
	
	./manage_my_process &
	echo "$!" > $file
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
