#!/usr/bin/env bash
#this script runs to infinity and resist kill order by pkill and
#instead prints a mesaage

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
