#!/usr/bin/env bash
#this script will print things at the 4th, 9th and 17th interation

n=1
while [ $n -le 20 ]
do
	echo "$n"

	case $n in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac

	((n++))
done
