#!/usr/bin/env bash
#display the numerical values of the clock in hours and minute
#hours from 0 to 12, minuites from 1 to 59

hour=0
while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	minutes=1
	while [ $minutes -le 59 ]
	do
		echo "$minutes"
		((minutes++))
	done
	((hour++))
done
