#!/usr/bin/env bash
#This script willc ofigure nginx to be run as a user called ngix
#This so that if ever a hacker has access to ur web server he won't
#he won't have a root access to the web server
pkill -9 apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 755 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
