#!/bin/bash

# Get the PID of the Gunicorn master process
master_pid=$(pgrep -f 'gunicorn: master')

if [[ -z $master_pid ]]; then
  echo "Gunicorn master process not found. Make sure Gunicorn is running."
  exit 1
fi

echo "Reloading Gunicorn gracefully..."

# Send a HUP signal to the Gunicorn master process
kill -HUP $master_pid

echo "Gunicorn reloaded gracefully."
